hmcts/div-common-lib

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/models/response/ValidationResponse.java
src/main/java/uk/gov/hmcts/reform/divorce/validation/rules/RulesConfig.java

https://tools.hmcts.net/jira/browse/DIV-5684
Added RulesConfig class to be able to use rules in validation. It was failing start up.
```
[x] Yes
[ ] No
```

DIV-4454: add rules config

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/models/request/Address.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/CaseDataContent.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/CaseDetails.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/CollectionMember.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/Connections.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/CoreCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/DivorceSession.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/Document.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/DocumentLink.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/Event.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/Gender.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/Payment.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/PaymentCollection.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/RejectReasonAddressType.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/SubmitEvent.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/UploadedFile.java
src/main/java/uk/gov/hmcts/reform/divorce/models/request/ValidationRequest.java
src/main/java/uk/gov/hmcts/reform/divorce/models/response/ValidationResponse.java
src/main/java/uk/gov/hmcts/reform/divorce/utils/DateUtils.java
src/test/java/uk/gov/hmcts/reform/divorce/utils/DateUtilsTest.java
src/test/java/uk/gov/hmcts/reform/divorce/validation/rules/d8/D8MarriageDateTest.java
src/test/java/uk/gov/hmcts/reform/divorce/validation/rules/d8/D8ReasonForDivorceTest.java

https://tools.hmcts.net/jira/browse/DIV-5684
Refactoring
```
[x] Yes
[ ] No
```

DIV-5684: refactoring

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/formatter/mapper/DivorceCaseToDnClarificationMapper.java
src/test/java/uk/gov/hmcts/reform/divorce/formatter/mapper/divorcetoccdformat/DivorceCaseToDnClarificationMapperUTest.java

Fixed NPE issues on DN Clarification Mapper

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/model/documentupdate/GeneratedDocumentInfo.java
src/test/java/uk/gov/hmcts/reform/divorce/formatter/impl/CaseFormatterServiceImplUTest.java
src/test/java/uk/gov/hmcts/reform/divorce/formatter/mapper/DocumentCollectionDocumentRequestMapperUTest.java

Updated   GeneratedDocumentInfo
```
[ ] Yes
[x] No
```

unify GeneratedDocumentInfo, and remove it from COS

---

build.gradle
lombok.config

Issue described here:
https://github.com/spring-projects/spring-boot/issues/12568
I have tested it locally. Tests that were broken before on COS are now passing.
```
[x] Yes
[ ] No
```

added lombok.config file to fix serializing issue

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/utils/DateUtils.java
src/test/java/uk/gov/hmcts/reform/divorce/utils/DateUtilsTest.java

https://tools.hmcts.net/jira/browse/DIV-6339
and all others tickets to generate documents.
```
formatDateWithCustomerFacingFormat(LocalDate.now());
formatDateWithCustomerFacingFormat("2010-10-10");
```

1.1.23: one way of formatting dates for emails and docs - formatDateWithCustomerFacingFormat

---

.github/workflows/gradle.yml
build.gradle

We're currently releasing as part of the PR pipeline.
```
[ ] Yes
[ x ] No
```

Checking artefact, but not releasing it in PR pipeline.

---

.github/workflows/gradle.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/RPET-263

RPET-263: upgraded to java 11

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/DivorceGeneralOrder.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/Document.java
src/main/java/uk/gov/hmcts/reform/divorce/model/parties/DivorceParty.java
src/main/java/uk/gov/hmcts/reform/divorce/model/parties/DivorcePartyNotFoundException.java
src/test/java/uk/gov/hmcts/reform/divorce/model/parties/DivorcePartyTest.java

DIV-6496: Adding classes used by both CFS and COS to the common lib

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/AosCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/CaseLink.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/CollectionMember.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/CoreCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/DnCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/DnRefusalCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/payment/Payment.java
src/main/java/uk/gov/hmcts/reform/divorce/model/payment/PaymentCollection.java
src/main/java/uk/gov/hmcts/reform/divorce/model/usersession/YesNoNeverAnswer.java
src/test/java/uk/gov/hmcts/reform/divorce/model/usersession/YesNoNeverAnswerTest.java

This is the start of a migration of some logic from CFS into div-commons-lib.
```
[ ] Yes
[ X ] No
```

DIV-5908: Moving some CFS beans and their tests to div-common

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/AosCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/usersession/DivorceSession.java
src/test/resources/fixtures/ccdtodivorcemapping/ccd/decree-nisi-outcome.json
src/test/resources/fixtures/ccdtodivorcemapping/divorce/decree-nisi-outcome.json

https://tools.hmcts.net/jira/browse/DIV-6180
Returning `servedByProcessServer` field to divorce session data.
```
[ ] Yes
[x] No
```

DIV-6180-Served-by-process-server-DN-your-husband-wife-response-page

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/mapper/CCDCaseToDivorceMapper.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/AosCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/CoreCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/ServiceApplication.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/ServiceApplicationData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/usersession/DivorceSession.java
src/test/java/uk/gov/hmcts/reform/divorce/mapper/ccdtodivorceformat/ServiceApplicationMapperUTest.java
src/test/resources/fixtures/ccdtodivorcemapping/ccd/aos.json
src/test/resources/fixtures/ccdtodivorcemapping/ccd/service-application-case.json
src/test/resources/fixtures/ccdtodivorcemapping/divorce/aos.json
src/test/resources/fixtures/ccdtodivorcemapping/divorce/service-application-case.json
src/test/resources/fixtures/divorcetoccdmapping/ccd/aos.json
src/test/resources/fixtures/divorcetoccdmapping/divorce/aos.json
src/test/resources/fixtures/divorcetoccdmapping/divorce/dn.json

https://tools.hmcts.net/jira/browse/DIV-6647
Handle extracting of values 'ServiceApplicationType' and 'ServiceApplicationGranted' from last completed Service application.
```
[ ] Yes
[x] No
```

DIV-6647: Extract values from last completed service application

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/AosCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/usersession/DivorceSession.java
src/test/resources/fixtures/ccdtodivorcemapping/ccd/decree-nisi-outcome.json
src/test/resources/fixtures/ccdtodivorcemapping/divorce/decree-nisi-outcome.json

https://tools.hmcts.net/jira/browse/DIV-6645
Add `servedByAlternativeMethod`
COS: https://github.com/hmcts/div-case-orchestration-service/pull/1164
CFS: 
CMS: https://github.com/hmcts/div-case-maintenance-service/pull/379
```
[ ] Yes
[ ] No
```

6645: Align common lib

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/mapper/CCDCaseToDivorceMapper.java
src/main/java/uk/gov/hmcts/reform/divorce/mapper/DivorceCaseToCCDMapper.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/CoreCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/usersession/DivorceSession.java
src/main/java/uk/gov/hmcts/reform/divorce/validation/rules/d8/D8JurisdictionConnectionNewPolicy.java
src/test/java/uk/gov/hmcts/reform/divorce/validation/rules/d8/D8JurisdictionConnectionNewPolicyTest.java
src/test/resources/fixtures/divorcetoccdmapping/ccd/d8document.json
src/test/resources/fixtures/divorcetoccdmapping/divorce/d8-document.json

Add support for new Jurisdiction connection new policy.
```
[ ] Yes
[x] No
```

Add jurisdiction connection new policy. DO NOT MERGE

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/model/usersession/DivorceSession.java

Add new legal connection field to divorce session

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/CoreCaseData.java

RPET-664 - Add new policy connection to ccd

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/mapper/CCDCaseToDivorceMapper.java
src/main/java/uk/gov/hmcts/reform/divorce/mapper/DivorceCaseToCCDMapper.java

RPET-664: Update mapping for new legal connection policy

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/mapper/CCDCaseToDivorceMapper.java
src/main/java/uk/gov/hmcts/reform/divorce/mapper/DivorceCaseToCCDMapper.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/CoreCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/model/usersession/DivorceSession.java
src/test/resources/fixtures/divorcetoccdmapping/ccd/d8document.json
src/test/resources/fixtures/divorcetoccdmapping/divorce/d8-document.json

+ Should not have been merged into master untill it's ready for release
Need to use gradle composite build to test locally
```
[ ] Yes
[ ] No
```

Remove Brexit related changes from master

---

build.gradle
src/main/java/uk/gov/hmcts/reform/divorce/mapper/CCDCaseToDivorceMapper.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/Organisation.java
src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/OrganisationPolicy.java
src/test/java/uk/gov/hmcts/reform/divorce/mapper/ccdtodivorceformat/RespondentOrganisationPolicyToDivorceMapperUTest.java
src/test/resources/fixtures/ccdtodivorcemapping/ccd/respondent-organisation-policy.json
src/test/resources/fixtures/ccdtodivorcemapping/divorce/respondent-organisation-policy.json

https://tools.hmcts.net/jira/browse/DIV-6872
Map respondent organisation ID from CCD to Divorce session
```
[ ] Yes
[ ] No
```

DIV-6872: Map respondent organisation ID from CCD to Divorce session

---

.github/workflows/gradle.yml
.github/workflows/jitpack_build.yml
build.gradle
jitpack.yml

DFR-20
Migrate to Jitpack from Bintray
```
[ ] Yes
[ x] No
```

DFR-20: Migrate to Jitpack from Bintray

---

src/main/java/uk/gov/hmcts/reform/divorce/model/ccd/CoreCaseData.java
src/main/java/uk/gov/hmcts/reform/divorce/validation/rules/compilers/RuleCompilerFactory.java
src/main/java/uk/gov/hmcts/reform/divorce/validation/rules/d8/D8ReasonForDivorce.java

add checks to Previous Divorce and Rejection Reasons for DN Refusal
